---

- name: fetch vim appimage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage
    dest: /tmp
    mode: '0744'

- name: Copy file with owner and permissions
  copy:
    src: /tmp/nvim.appimage
    dest: /usr/local/bin/nvim
    owner: thomas
    group: thomas
    mode: '0744'
    remote_src: yes
  become: yes

- name: create neovim autoload folder
  file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory
    mode: '0755'

- name: Download vim-plug.vim for neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
    mode: '0755'
    force: true

- name: create nvim config dir
  ansible.builtin.file:
    path: ~/.config/nvim/
    state: directory
    mode: '0755'

- name: set up nvim config
  file:
    src: "{{ dotfiles_folder }}/nvim/init.vim"
    dest: ~/.config/nvim/init.vim
    state: link

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: install curl if not installed
  include_role:
    name: curl
  when: ansible_facts.packages['curl'] is not defined
  
- name: install vim plugins
  shell: "nvim --headless +PlugInstall +qall"
